### ISSUE TITLE
Forward event notification plugin runs only once

### ISSUE THREAD

**Issue by sha-265** [darosior/clightningjs#3] opened 2020-01-16 17:11 UTC
Hi,

I build a plugin using `clightningjs` package that subscribe to `forward_event` notifications, but the plugin is notify only about the first payment routed through the node that runs the plugin. After the first routed payment the script is not running.

This is the plugin code:
```
listenPlugin.subscribe('forward_event');
listenPlugin.notifications.forward_event.on('forward_event', (params) => {
  if ( params.forward_event.status == "settled" ) {
     fs.writeFile('log', JSON.stringify(params.forward_event), () => {});
  }
});

listenPlugin.start();
```

And I'm running my c-lightning (v0.8.0) node like this: `lightningd --plugin="/home/ln/forward-notify.js"`

Any idea way?

Thanks.

**Comment by darosior** [comment] 2020-01-19 15:14
Checking this now

**Comment by darosior** [comment] 2020-01-19 15:33
@sha-265 
I'm not able to reproduce, I've pushed a test so you can check if the issue is on your own. Here is how I tried :
I've seup a regtest using my [regtest-manager](https://github.com/darosior/regtest-manager) with channels like
```
A -> B -> C
```
Then I started my test plugin on the node `B` with a code similar to your above, and made some payments forwarding through the node `B`. I then checked the log file, all the forwards were here.
Here are the commands
```
$ start_regtest 3
$ fund_regtest
$ lcreg2 plugin start $PWD/test/forward.js
$ lcreg1 connect $(lcreg3 getinfo |jq -r .id)@127.0.0.1:11003
$ for i in $(seq 5); do lcreg1 pay $(lcreg3 invoice 1000 "$i" desc |jq -r .bolt11);done
{
   "id": 1,
   "payment_hash": "c833eabfe80820d491393beae2c0b56d788b108f964ade3ca055fdbdf623c543",
   "destination": "03aec3564df6115ff7d4cfe0a9a28228a2b4421ff1bdf887fbb7a3e548cfb9b9bf",
   "msatoshi": 1000,
   "amount_msat": "1000msat",
   "msatoshi_sent": 1001,
   "amount_sent_msat": "1001msat",
   "created_at": 1579447887,
   "status": "complete",
   "payment_preimage": "782c56d4e1dae9aee1fcb8d17bf8988b364d6b8ab30e8c463cd99700edc4fcde",
   "bolt11": "lnbcrt10n1p0zgaj0pp5eqe740lgpqsdfyfe804w9s94d4ugkyy0je9du09q2h7mma3rc4psdq8v3jhxccxqyjw5qcqp2sp5mpm5wlrl0vgcgw2whgrczcwly3jgqlax3cy3x6zk8746wmgrlzxsrzjqw99a5mayxcflcu7d3fn39afnc9z5twlauww9mzuknzqhv57w09xyqqqhgqqqqsqqqqqqqqpqqqqqzsqqc9qy9qsq3hy683lfa7wts8dww0u687ng44qr0n0wdqkj3fcqk6fysj9auw0svprkusanpdpa5544h7cxm2jt0t69wkz2xuvx09ftwf94jvtx43sp5f0jwx"
}
{
   "id": 2,
   "payment_hash": "840ef6c0ace63a538258888de10e6edd9490b68c24f8bb762018a33ee19ac00b",
   "destination": "03aec3564df6115ff7d4cfe0a9a28228a2b4421ff1bdf887fbb7a3e548cfb9b9bf",
   "msatoshi": 1000,
   "amount_msat": "1000msat",
   "msatoshi_sent": 1001,
   "amount_sent_msat": "1001msat",
   "created_at": 1579447888,
   "status": "complete",
   "payment_preimage": "18fa7879a951ed9fd0b20bc8db990932807b346f3c383a56ca75f8065f574c17",
   "bolt11": "lnbcrt10n1p0zgajspp5ss80ds9vuca98qjc3zx7zrnwmk2fpd5vynutka3qrz3nacv6cq9sdq8v3jhxccxqyjw5qcqp2sp53m4ynsy83a62memwydcdf5tmh8nn6fxf5uhxes2g550g4s2culrsrzjqw99a5mayxcflcu7d3fn39afnc9z5twlauww9mzuknzqhv57w09xyqqqhgqqqqsqqqqqqqqpqqqqqzsqqc9qy9qsqsr3n4yuf0aptwcluapledlkdj078y0n0dnp8d3q8qfds7c0sderj4rnepefygyw7c5huwqd35svle6mf4zxjq09jtgd8yfcyql03nqsq290tz2"
}
{
   "id": 3,
   "payment_hash": "d53c6523205fc114353e9c73c4c8d01490c906ecc6985a94f40f27238087f295",
   "destination": "03aec3564df6115ff7d4cfe0a9a28228a2b4421ff1bdf887fbb7a3e548cfb9b9bf",
   "msatoshi": 1000,
   "amount_msat": "1000msat",
   "msatoshi_sent": 1001,
   "amount_sent_msat": "1001msat",
   "created_at": 1579447888,
   "status": "complete",
   "payment_preimage": "dc1de9e0405966ee332a4d106af567556a8f9466dbb10ccf74d95e57ccf02df9",
   "bolt11": "lnbcrt10n1p0zgajspp5657x2geqtlq3gdf7n3eufjxszjgvjphvc6v94985punj8qy8722sdq8v3jhxccxqyjw5qcqp2sp5yjxdg4usch38pegpdmm7laqdcr5wpdd3mytwr4keecgtuezjcykqrzjqw99a5mayxcflcu7d3fn39afnc9z5twlauww9mzuknzqhv57w09xyqqqhgqqqqsqqqqqqqqpqqqqqzsqqc9qy9qsq2kzw6xj42j794jrwprx24vs3253renhzqvrncmeau3djgtpjgv3rygfvfrc6pq6v29hkjaksgvaflz8ks03790qv7wg6xyvn32k6qtcphd8jvs"
}
{
   "id": 4,
   "payment_hash": "025cd63f5594bab621199c30e7f6c84aa4f9979262f6f4f9148c19a99ccefd90",
   "destination": "03aec3564df6115ff7d4cfe0a9a28228a2b4421ff1bdf887fbb7a3e548cfb9b9bf",
   "msatoshi": 1000,
   "amount_msat": "1000msat",
   "msatoshi_sent": 1001,
   "amount_sent_msat": "1001msat",
   "created_at": 1579447888,
   "status": "complete",
   "payment_preimage": "832e5fe707f1820f21a299d7ea400f8a32efc7e4de5cfc644571cfdbea03c711",
   "bolt11": "lnbcrt10n1p0zgajspp5qfwdv064jjatvggenscw0akgf2j0n9ujvtm0f7g53sv6n8xwlkgqdq8v3jhxccxqyjw5qcqp2sp53mlduqtgv432evqgehhxvt49tfhgx0vf63jtgvgrar599e32cnvqrzjqw99a5mayxcflcu7d3fn39afnc9z5twlauww9mzuknzqhv57w09xyqqqhgqqqqsqqqqqqqqpqqqqqzsqqc9qy9qsqnfnn9fl7yw8rjnjq8cntuumh37rcrs4u6m36yxvey0nsfmterf58k0q98rw0egrgg3ww4y933cy2uwh9z8qypamzxfp02hpx3dt842sp4x795g"
}
{
   "id": 5,
   "payment_hash": "180dbabb1a2c38e230a7710db5bba76ab68bd27a06e1ee821b3c0d058a127b02",
   "destination": "03aec3564df6115ff7d4cfe0a9a28228a2b4421ff1bdf887fbb7a3e548cfb9b9bf",
   "msatoshi": 1002,
   "amount_msat": "1002msat",
   "msatoshi_sent": 1003,
   "amount_sent_msat": "1003msat",
   "created_at": 1579447889,
   "status": "complete",
   "payment_preimage": "fe934ed3c526b254c5b0d2303c188f28ba8c2b9c4594d4b21f76e8ebf4f4b55b",
   "bolt11": "lnbcrt10n1p0zgaj3pp5rqxm4wc69suwyv98wyxmtwa8d2mgh5n6qms7aqsm8sxstzsj0vpqdq8v3jhxccxqyjw5qcqp2sp5yayeyvxtkcddfaskvn6m0pcdudw29yv6mp6ra7chxk6eg6ljl6ssrzjqw99a5mayxcflcu7d3fn39afnc9z5twlauww9mzuknzqhv57w09xyqqqhgqqqqsqqqqqqqqpqqqqqzsqqc9qy9qsqsch5wt5vdwlux4ffvjaru22ljzuxaatqpdsdz8csj05npf5hpdh45cssm0efjfhy42qezvcm0eswu6lpyl0luz5jhcfexzlfy4qssxqpt9utv4"
}
$ cat regtest/lndir2/regtest/log 
{"payment_hash":"c833eabfe80820d491393beae2c0b56d788b108f964ade3ca055fdbdf623c543","in_channel":"186x1x0","out_channel":"186x2x0","in_msatoshi":1001,"in_msat":"1001msat","out_msatoshi":1000,"out_msat":"1000msat","fee":1,"fee_msat":"1msat","status":"settled","received_time":1579447887.745,"resolved_time":1579447888.02}

{"payment_hash":"840ef6c0ace63a538258888de10e6edd9490b68c24f8bb762018a33ee19ac00b","in_channel":"186x1x0","out_channel":"186x2x0","in_msatoshi":1001,"in_msat":"1001msat","out_msatoshi":1000,"out_msat":"1000msat","fee":1,"fee_msat":"1msat","status":"settled","received_time":1579447888.204,"resolved_time":1579447888.404}

{"payment_hash":"d53c6523205fc114353e9c73c4c8d01490c906ecc6985a94f40f27238087f295","in_channel":"186x1x0","out_channel":"186x2x0","in_msatoshi":1001,"in_msat":"1001msat","out_msatoshi":1000,"out_msat":"1000msat","fee":1,"fee_msat":"1msat","status":"settled","received_time":1579447888.584,"resolved_time":1579447888.784}

{"payment_hash":"025cd63f5594bab621199c30e7f6c84aa4f9979262f6f4f9148c19a99ccefd90","in_channel":"186x1x0","out_channel":"186x2x0","in_msatoshi":1001,"in_msat":"1001msat","out_msatoshi":1000,"out_msat":"1000msat","fee":1,"fee_msat":"1msat","status":"settled","received_time":1579447888.968,"resolved_time":1579447889.132}

{"payment_hash":"180dbabb1a2c38e230a7710db5bba76ab68bd27a06e1ee821b3c0d058a127b02","in_channel":"186x1x0","out_channel":"186x2x0","in_msatoshi":1003,"in_msat":"1003msat","out_msatoshi":1002,"out_msat":"1002msat","fee":1,"fee_msat":"1msat","status":"settled","received_time":1579447889.319,"resolved_time":1579447889.491}
```

**Comment by darosior** [comment] 2020-03-25 10:08
@sha-265 This's been 2 months now and I still cannot reproduce. Closing.

**Closed by darosior** 2020-03-25 10:08 UTC
